server:
    port: 8083
spring:
    h2:
        console: null
        enabled: true
    jpa:
        properties:
            hibernate: {generateStatistics: true, formatSql: true}
        showSql: true
    data:
        mongodb:
            uri: mongodb://estoqueservicedb
            database: servicedb
    kafka:
        producer:
            bootstrap-servers: '${SPRING_KAFKA_BOOTSTRAP_SERVER}'
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties: {spring: {json: {add: {type: {headers: false}}}}}
        consumer:
            bootstrap-servers: '${SPRING_KAFKA_BOOTSTRAP_SERVER}'
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: com.uaipago.estoque.model.OrdemCompraDeserializer
            properties: {spring: {json: {trusted: {packages: '*'}}}}
